config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # get 'customers/index'
  # get 'customers/new'
  # get 'customers/create'
  # get 'customers/edit'
  # get 'customers/update'
  # get 'customers/show'
  # get 'customers/destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :customers
  root 'customers#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :customer
  validates :body,        presence: true
  validates :customer_id, presence: true  
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :customers
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :company
  belongs_to :post

  has_many :comments
############ ここから追加
  validates :family_name, presence: true, length: { maximum: 20 }
  validates :given_name, presence: true, length: { maximum: 20 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: true
  # validates :company_id, presence: true
############ ここまで追加

  def full_name
    family_name + given_name
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :customers
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:family_name, :given_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:family_name, :given_name])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
# 下記の1行追加
  before_action :authenticate_user!
  before_action :set_customer, only: [:show, :edit, :update, :destroy] #追加

  def index
    @q = Customer.includes(:post, :company).ransack(params[:q])
    @customers = @q.result.page(params[:page]).per(10)
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)
    if @customer.save
      redirect_to @customer
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @customer.update(customer_params)
      redirect_to @customer
    else
      render :edit
    end
  end

  def show
  end

  def destroy
    @customer.destroy
    redirect_to customers_path
  end

  private

  def customer_params
    params.require(:customer).permit(
      :family_name,
      :given_name,
      :email,
      :company_id,
      :post_id
      )
  end

# ↓追加
  def set_customer
    @customer = Customer.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= form_with model: customer, local: true do |form| %>

<!-- 以下を追加 -->
  <% if customer.errors.any? %>
    <div class="alert alert-danger">
      <p><b><%= customer.errors.count %>件のエラーがあります</b></p>

      <ul>
      <% customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= form.label :family_name %><br>
    <%= form.text_field :family_name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :given_name %><br>
    <%= form.text_field :given_name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :email %><br>
    <%= form.text_field :email, class: "form-control" %>
  </div>
    <div class="form-group">
    <%= form.label :company_id %>
    <%= form.collection_select :company_id, Company.all, :id, :name , { include_blank: "会社を選択してください" },  { class: "form-control" } %>
    </div>
    <div class="form-group">
    <%= form.label :post_id %>
    <%= form.collection_select :post_id, Post.all, :id, :position_name , { include_blank: "役職を選択してください" },  { class: "form-control" } %>
    </div>

  <%= form.submit class: "btn btn-primary" %>

  <% if customer.persisted? %>
    <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#delete-customer">顧客情報を削除する</button>
    <%= link_to '戻る', customer_path(@customer), class: "btn btn-secondary" %>
  <% end %>

<% end %>

<div class="modal fade" id="delete-customer">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
      <h5 class="modal-title" id="exampleModalLabel">顧客情報の削除</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p><%= @customer.family_name %>さんを削除しますか？</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">キャンセル</button>
        <%= link_to '削除する', @customer, method: :delete, class: "btn btn-danger" %>
      </div>
    </div>
  </div>
</div>

app/views/customers/edit.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1>顧客情報の編集</h1>
    <%= render partial: 'form', locals: { customer: @customer } %>
  </div>
</div>

app/views/customers/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1>顧客情報一覧</h1>
  </div>
</div>
<div class="row">
  <div class="col-lg-6">
    <p>お客様情報が表示されます。</p>
  </div>
  <div class="col-lg-6">
    <%= link_to '顧客登録', new_customer_path, class: "btn btn-info float-right mb-3" %>
  </div>
</div>


<%= search_form_for @q do |f| %>
  <div class="row">
    <div class="col-sm-3 col-xs-12">
      <div class="form-group">
        <%= f.label :family_name_cont, '姓' %>
        <%= f.search_field :family_name_cont, class: "form-control input-sm" %>
      </div>
    </div>
    <div class="col-sm-3 col-xs-12">
      <div class="form-group">
        <%= f.label :given_name_cont, '名' %>
        <%= f.search_field :given_name_cont, class: "form-control input-sm" %>
      </div>
    </div>
    <div class="col-sm-2 col-xs-12">
      <div class="form-group">
        <%= f.label :email_cont, '電子メール' %>
        <%= f.search_field :email_cont, class: "form-control input-sm" %>
      </div>
    </div>
    <div class="col-sm-2 col-xs-12">
      <div class="form-group">
        <%= f.label :company_name_cont, '会社名' %>
        <%= f.search_field :company_name_cont, class: "form-control input-sm" %>
      </div>
    </div>
    <div class="col-sm-2 col-xs-12">
      <div class="form-group">
        <%= f.label :post_position_name_cont, '役職名' %>
        <%= f.search_field :post_position_name_cont, class: "form-control input-sm" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12 mx-auto">
      <%= f.submit "検索", class: "btn btn-info" %>
      <%= link_to "リセット", request.path, class:"btn btn-secondary" %>
    </div>
  </div>
<% end %>
<hr />


<table class="table table-striped table-hover">
  <thead class="thead-dark">
    <th><%= sort_link(@q, :family_name, "姓") %></th>
    <th><%= sort_link(@q, :given_name, "名") %></th>
    <th><%= sort_link(@q, :email, "電子メール") %></th>
    <th><%= sort_link(@q, :company_name, "所属会社") %></th>
    <th><%= sort_link(@q, :post_position_name, "役職") %></th>
    <th>リンク</th>
  </thead>
  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.family_name %></td>
        <td><%= customer.given_name %></td>
        <td><%= customer.email %></td>
        <td><%= customer.company.name %></td>
        <td><%= customer.post.position_name %></td>
        <td><%= link_to '詳細', customer, class: "btn btn-secondary btn-xs" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @customers %>

app/views/customers/new.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1>顧客新規登録</h1>
    <%= render partial: 'form', locals: { customer: @customer } %>
  </div>
</div>

app/views/customers/show.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1>顧客詳細</h1>
    <dl>
      <dt>お名前</dt>
      <dd class="mb-2 ml-4"><%= @customer.full_name %></dd>
      <dt>電子メール</dt>
      <dd class="mb-2 ml-4"><%= @customer.email %></dd>
<!-- 下記の2行を追加 -->
      <dt>会社名</dt>
      <dd class="mb-2 ml-4"><%= @customer.company.name %></dd>
      <dt>役職</dt>
      <dd class="mb-2 ml-4"><%= @customer.post.position_name %></dd>
    </dl>
    <%= link_to '編集', edit_customer_path(@customer), class: "btn btn-primary" %>
    <%= link_to '戻る', customers_path, class: "btn btn-secondary" %>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary mb-3">
  <div class="container">
    <!-- ★★★★下記の#を後ほど正しいURLに変更 -->
    <%= link_to "顧客管理システム", customers_path, class: "navbar-brand" %>
    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="ナビゲーションの切替">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "設定変更", edit_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "新規登録", new_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "ログイン", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SpartaCrm</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'layouts/header' %>
    <div class="container">

    <% if notice.present? %>
        <div class="alert alert-dismissable alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <span><%= notice %></span>
        </div>
      <% end %>

      <% if alert.present? %>
        <div class="alert alert-dismissable alert-danger">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <span><%= alert %></span>
        </div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>